### PR TITLE
Typical Rookie Mistake

### PR DESCRIPTION
**Pull request by BSherb**
Forgot to pack my PBO

### CODE REVIEW

**Comment by Eogos** [comment]
of course you did, nice job

**Comment by BSherb** [comment]
Forgetting a file is better than nothing at all!

**Comment by Eogos** [comment]
forgetting a file means there is nothing at all

**Comment by BSherb** [comment]
available to the Arma Server, but the files are still there :3

**Comment by Eogos** [comment]
do you think people are getting annoyed at the amount of embedded github messages yet?

**Comment by BSherb** [comment]
Doesn't matter, we can drown them out with our oversized messages. Plebs

**Comment by Eogos** [comment]
fair point

**Pull request merged**
